### ISSUE TITLE
check-rabbitmq-node-health.rb - option flags duplicated

### ISSUE THREAD

**Issue by jwatroba** [sensu-plugins/sensu-plugins-rabbitmq#19]
All of the options for warning/critical for memory, socket and file descriptor usage are using -m and -c, these seem to be colliding and returning incorrect results, also they don't allow the user to set different thresholds for these three different stats. I feel like these should use different flags.

**Comment by eheydrick** [comment]
Nice catch. Those should definitely be unique options. I'd take a PR to make those unique.

**Comment by eheydrick** [comment]
Fixed in version [1.0.0](https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/1.0.0).
