### ISSUE TITLE
Move to latest bunny

### ISSUE THREAD

**Issue by eheydrick** [sensu-plugins/sensu-plugins-rabbitmq#23]
We should move to bunny 2.x now that we're dropping Ruby 1.9.3 support.

https://github.com/ruby-amqp/bunny/blob/master/ChangeLog.md

**Comment by EslamElHusseiny** [comment]
I've Raised a PR to fix this issue #41
I've also published a temp gem https://rubygems.org/gems/sensu-plugins-rabbitmq-temp till we get the fix PR merged and the gem published.

**Comment by eheydrick** [comment]
[2.0.0](https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/2.0.0) is live on rubygems.
