### ISSUE TITLE
FreeBSD: gcc error: command not found

### ISSUE THREAD

**Issue by dR3b** [sensu-plugins/sensu-plugins-rabbitmq#33]
Please use **clang** and not **gcc** on FreeBSD! 
With:

```
ln -snfv /usr/bin/clang /usr/bin/gcc
```

... all is compiling fine.
Thanks

**Comment by majormoses** [comment]
@dR3b can you please identify which check you are seeing a gcc dependency in?

**Comment by dR3b** [comment]
It's over a year since I reported this. Now it builds without problems. Thanks.

**Comment by majormoses** [comment]
well glad its fixed...wish someone had addressed it sooner...
