### ISSUE TITLE
sensu update 0.23 -> 0.24 compatibility

### ISSUE THREAD

**Issue by driegel** [sensu-plugins/sensu-plugins-rabbitmq#35]
Hello,

This plugin worked well for me with sensu-0.23.2. Now my systems are running 0.24.1 and I get the following error:

```
/opt/sensu/embedded/bin//check-rabbitmq-amqp-alive.rb -u <...> -p <...>
/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1436:in `block in activate_dependencies': can't satisfy 'amq-protocol (= 1.9.2)', already activated 'amq-protocol-2.0.1' (Gem::LoadError)
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `block in activate_bin_path'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `synchronize'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:279:in `activate_bin_path'
	from /opt/sensu/embedded/bin//check-rabbitmq-amqp-alive.rb:22:in `<main>'
```

It seems that somehow amq-protocol got updated which causes an dependency issue ???

Thanks!

**Comment by driegel** [comment]
One workaround: installing both amq-protocoll versions:

```
/opt/sensu/embedded/bin/gem list | grep amq
amq-protocol (2.0.1, 1.9.2)
```

**Comment by cwjohnston** [comment]
Looks like the dependency changed here https://github.com/sensu/sensu-transport/pull/29 and here https://github.com/sensu/sensu/pull/1026

**Comment by cwjohnston** [comment]
Seems to me that we need to update our dependency on amq-protocol to match Sensu. I believe this would be a breaking change for the same reasons described in #23. Assigning this to v2.0.0 milestone.

**Comment by thecosmicfrog** [comment]
Issue is affecting me too. @driegel's workaround works for now.

**Comment by chuckwired** [comment]
Used the workaround mentioned above, still seems to be a problem in Sensu 0.25.5

**Comment by EslamElHusseiny** [comment]
I've Raised a PR to fix this issue https://github.com/sensu-plugins/sensu-plugins-rabbitmq/pull/41
I've also published a temp gem https://rubygems.org/gems/sensu-plugins-rabbitmq-temp till we get the fix PR merged and the gem published.

**Comment by eheydrick** [comment]
[2.0.0](https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/2.0.0) is live on rubygems.
