### ISSUE TITLE
sensu-plugins breaks after 0.25 version update

### ISSUE THREAD

**Issue by AMKamel** [sensu-plugins/sensu-plugins-rabbitmq#36]
Hello,
After sensu package got updated to version 0.25 on my centos 7 server the plugins no longer works.
It give the following errors:
http://pastebin.com/54Tqm6jY
![selection_234](https://cloud.githubusercontent.com/assets/14953512/16036362/38224d06-3224-11e6-88bf-e4e6141fcd69.png)

**Comment by mattyjones** [comment]
@AMKamel 

I updated the dependency and cut a new version of the plugin that should fix this issue going forward.
