### ISSUE TITLE
Support loading username/password from config file

### ISSUE THREAD

**Issue by bootswithdefer** [sensu-plugins/sensu-plugins-rabbitmq#42]
Support loading username/password from config file so that passwords are not exposed.  For example see how the MySQL plugin does it: https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-alive.rb#L72-L80

**Comment by majormoses** [comment]
I would love a contribution to support such, any chance you would be open to submitting a PR?

**Comment by bootswithdefer** [comment]
Submitted PR #60

**Comment by majormoses** [comment]
released as: https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/3.0.0
