### ISSUE TITLE
check-rabbitmq-node-health is missing options for checking number of processes and disk usage

### ISSUE THREAD

**Issue by psyhomb** [sensu-plugins/sensu-plugins-rabbitmq#44]
Is there any chance to someone can implement this?

**Comment by psyhomb** [comment]
Nice, that's exactly what I asked for!

**Comment by majormoses** [comment]
@psyhomb yup sorry for the delay I have reviewed it and its almost ready for merge. Watch the pr and if I don't make a release within 24 hours of merging ping me.

**Comment by majormoses** [comment]
I have released and this can be closed.
