### ISSUE TITLE
check-rabbitmq-node-health fails on OSX because fd_used = unknown

### ISSUE THREAD

**Issue by thisisjaid** [sensu-plugins/sensu-plugins-rabbitmq#47]
It seems that on OSX (tested on OSX 10.10 and 10.9) the RabbitMQ API cannot obtain the current number of used file descriptors and the value of fd_used becomes 'unknown' which generates the following exception:

`undefined method `fdiv' for nil:NilClass`

The error causes the probe to fail and return an UNKNOWN status code.

I've made an attempt at working around the problem by checking the fd_used variable is Numeric, though I'm not 100% sure that failing silently is the way to go. Unfortunately I don't know of any other way to obtain the fd_used value from RabbitMQ and getting it at the OS level may complicate things.

**Comment by thisisjaid** [comment]
Oh and please be gentle, this is my first PR

**Comment by eheydrick** [comment]
Fixed in #48 and released in 2.1.0.
