### ISSUE TITLE
Document Minimum permissions to use plugin to monitor RMQ

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-rabbitmq#59]
It appears that these checks require `administrator` as opposed to `monitoring` which is what I would have expected after reading this: https://www.rabbitmq.com/management.html.

If this really is the case (and not something wrong with our setup) then I can put together a pr to document this.

**Comment by majormoses** [comment]
Also we should include the dangers of using `administrator`, as this seems to be a bad idea in general as it would be able to drop queues and such which violates the principle of least privilege.

**Comment by majormoses** [comment]
So far these ones need to be allowed in addition to the `monitoring` tag:
```
:conf => '^aliveness-test$',
:write => '^amq\.default$',
:read => '.*'
```

This is not an extensive list, just what I found based on some initial testing. I will keep adding as I find more.

**Comment by windowsrefund** [comment]
I can confirm these permissions resulted in being able to use check-rabbitmq-alive.rb in order to verify my vhost is alive. This makes me happy.
