### ISSUE TITLE
Add extra metrics to metrics-rabbitmq-queue.rb

### ISSUE THREAD

**Issue by rthouvenin** [sensu-plugins/sensu-plugins-rabbitmq#61]
I have a use case where I would like to monitor the publish and deliver rates of particular queues. However the metrics provided by this plugin only gives the average egress rate.

Can we add more data to the queue metrics?

I can make a PR for these 2 extra metrics that I need, but I feel that rather than starting to do that, we should have an option to indicate which metrics to output, so that it's more flexible and anyone can benefit from it. However I am not sure of the best way to go about this. Maybe a dotted pattern to indicate the path to the value in the queue stats? E.g. : `message_stats.*.rate` or `backing_queue_status.avg_(in|e)gress_rate`.

Any thought?

**Comment by majormoses** [comment]
Yes an option with the same defaults that we currently have to maintain backwards compatibility.

**Comment by outworlder** [comment]
I have the same use-case to implement (publish, deliver rates). Do you require assistance? I see that there's already a proposed patch.

**Comment by majormoses** [comment]
@outworlder I have not gotten around to it yet (only been open 12 hours), most maintainers have their day jobs working for companies other than sensu. I will review this tonight though for sure.

**Comment by outworlder** [comment]
Awesome! If you need help, let me know.

**Comment by rthouvenin** [comment]
I made a big mistake in PR #62: When Rubocop told me to replace `metrics.match('backing_queue_status.avg')` with a `=~` operator, I did but for got to make the string into a regex and did not run again my tests...

So the command always ends in error with: `type mismatch: String given`.
Too bad that there are no automatic test, they would have caught this.

Submitting a PR right away.

**Comment by majormoses** [comment]
released hotfix: https://rubygems.org/gems/sensu-plugins-rabbitmq/versions/3.1.1

**Comment by majormoses** [comment]
@rthouvenin I assume this can be closed now, if you want to keep adding lets just do an issue per addition so this does not stay open forever.
