### ISSUE TITLE
Exchange metrics

### ISSUE THREAD

**Issue by rthouvenin** [sensu-plugins/sensu-plugins-rabbitmq#64]
I need to monitor some metrics about an exchange. Gathering the metrics is very similar to queue metrics, it took me a few minutes to copy and adapt `metrics-rabbitmq-queue.rb` and have something working. I am happy to PR, but wanted to check:

 - Is this something you are interested in?
 - Simply adding a mostly copy-pasted script feels bad, but then it seems that's how all scripts were done. For example `acquire_rabbitmq_info` is duplicated all over. Is there a reason, or is it just lazyness? :) Should I also just add my script?

**Comment by majormoses** [comment]
Oh there is certainly laziness for copy/paste, I would love to see the common logic be moved into libs and then leave use case specific logic to each check. More than happy to work with you on a refactor.

**Comment by rthouvenin** [comment]
Alright, sure I can chip in on a refactor. Does it make sense then that I PR the new "copy-pasted" metric, and have a separate issue for the refactoring?

**Comment by majormoses** [comment]
yes, let's refactor on its own pr with minimal functional change if possible.

**Comment by majormoses** [comment]
I created #65 for refactoring.

**Comment by rthouvenin** [comment]
Cool!

I'll be traveling for the next 10 days or so, should be able to give some time to it when back

**Comment by eheydrick** [comment]
Added in #66.
