### ISSUE TITLE
check-rabbitmq-node-health.rb check bug

### ISSUE THREAD

**Issue by rocdove** [sensu-plugins/sensu-plugins-rabbitmq#69]
in node_healthy! func
      # Parse our json data
      nodeinfo = JSON.parse(resource.get)[0]
only get the first node info is incomplete.
Singleton rabbitmq node is OK. when rabbitmq cluster，will not normal working.

**Comment by rocdove** [comment]
def node_healthy?
  ...
  JSON.parse(resource.get).each do |nodeinfo|
    # do something check
    ...
  end
  ...
end

this will be well.

**Comment by majormoses** [comment]
@rocdove thanks for the report, would you be willing to submit a pr to fix this?

**Comment by rocdove** [comment]
Let me try.

**Comment by rocdove** [comment]
@majormoses  Please give some advice for this commit. THX!

**Comment by majormoses** [comment]
@rocdove when I have some time absolutely.

**Comment by majormoses** [comment]
@rocdove overall it seems reasonable looking at the code just some minor tweaks. When you are ready create a PR:
- make sure to add a CHANGELOG entry under unreleased
- a testing artifact is provided, if not a unit test then a gist/screenshot with the input and output so we know it works.

I do use RMQ cluster for sensu so I will pull your code and try to test tomorrow.

**Comment by majormoses** [comment]
@rocdove realized this was already reported awhile go: https://github.com/sensu-plugins/sensu-plugins-rabbitmq/issues/43 I think we should close this and continue any further discussions over there.
