### ISSUE TITLE
400 "Bad Request" when running check-rabbitmq-queue.rb

### ISSUE THREAD

**Issue by akang1** [sensu-plugins/sensu-plugins-rabbitmq#77]
I had to upgrade my rabbit server to ubuntu 14.04 and now I getting the following error when running this command:

ruby /etc/sensu/plugins/check-rabbitmq-queue.rb --h localhost --user <user> --password <pw> --queue queuename -w 10 -c 20

Check failed to run: 400 "Bad Request", ["/usr/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'", "/var/lib/gems/2.3.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:59:in `fetch_uri'", "/var/lib/gems/2.3.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:24:in `query_api'", "/var/lib/gems/2.3.0/gems/carrot-top-0.0.7/lib/carrot-top.rb:28:in `method_missing'", "/etc/sensu/plugins/check-rabbitmq-queue.rb:106:in `run'", "/var/lib/gems/2.3.0/gems/sensu-plugin-2.3.0/lib/sensu-plugin/cli.rb:57:in `block in <class:CLI>'"]

ruby version: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux-gnu]
gem version: 2.5.2.1

I have sensu-plugin, cli, check and carrot-top gems installed. (I couldn't find "socket" to install but looking at my old server, it doesnt have that installed either).

Any help is appreciated.

**Comment by majormoses** [comment]
Thanks for reporting this and sorry about your issue. I will try to replicate this tonight some time. Regarding socket it comes from the standard library: https://ruby-doc.org/stdlib-2.4.2/libdoc/socket/rdoc/index.html

**Comment by majormoses** [comment]
Hmm I am getting a different error:
```
$ bundle exec ./bin/check-rabbitmq-queue.rb --host 172.16.250.184 --port 15671 --user sensu --password <REDACTED> --queue sensu -w 10 -c 20
Check failed to run: end of file reached, []
```

**Comment by majormoses** [comment]
@rthouvenin any chance you could take a look? It looks like it is coming from https://github.com/sensu-plugins/sensu-plugins-rabbitmq/blob/3.6.0/bin/check-rabbitmq-queue.rb#L74

**Comment by majormoses** [comment]
@akang1 what version of this gem are you using and do you see the same issue with newer versions? If you are using a recent version of this gem `--user` was replaced with `--username`.

**Comment by majormoses** [comment]
Either I am not authenticating correctly or something is horribly broken with carot top and the version of rabbitmq that I have installed:
```
irb(main):019:0> rabbitmq_info = CarrotTop.new(
irb(main):020:1* host: '172.16.250.184',
irb(main):021:1* port: 15671,
irb(main):022:1* user: '<REDACTED>',
irb(main):023:1* password: '<REDACTED>',
irb(main):024:1* ssl: false
irb(main):025:1> )
=> #<CarrotTop:0x00560239124a58 @rabbitmq_api="http://<REDACTED>:<REDACTED>@172.16.250.184:15671/api">
irb(main):026:0> rabbitmq_info.queues
EOFError: end of file reached
```

**Comment by rthouvenin** [comment]
I don't get any of your issues with RabbitMQ 3.6.2, ruby 2.3.0 and sensu-plugins-rabbitmq 3.6.0.

@akang1 From the stack trace (`method_missing` called on line 106), I can deduce that your version of the gem is 2.0.0 or older. This being said, I also made a test with v2.0.0 (just need to replace `username` with `user`), and it was still working fine for me.

**Comment by akang1** [comment]
@majormoses and @rthouvenin thank you guys so much for a quick response.

Your responses made me realize that I was using an old version of sensu-plugins-rabbitmq (specifically, check-rabbitmq-queue.rb).

Upgrading to the currently version + installing sensu-plugins-rabbitmq has fixed the issue that i was running into.

Once again, i appreciate your help!
